"""
Author: Y. Ahmed-Braimah
--- RNA-seq analysis using two genomes
--- Performs:
--- 1) Repeatmasking and repeat-aware alignment with HISAT2
--- 2) Transcript assembly with StringTie
--- 3) LiftOver of annotations between genomes with Liftoff
--- 4) Comparison of lifted annotations to native annotations with gffcompare
--- 5) Allele-specific expression analysis with GATK ASEReadCounter
"""

import json
import os
import re
import itertools
from os.path import join, basename, dirname
from os import getcwd
from subprocess import check_output

##--------------------------------------------------------------------------------------##
## Functions
##--------------------------------------------------------------------------------------##
  
# To print process messages
def message(x):
  print()

# To remove suffix from a string
def rstrip(text, suffix):
    if not text.endswith(suffix):
        return text
    return text[:len(text)-len(suffix)]

## define environment variables

##--------------------------------------------------------------------------------------##
## Global config files:
##--------------------------------------------------------------------------------------##

configfile: 'config.yml'

## Full path to a folder where final output files will be deposited.
OUT_DIR = config['OUT_DIR']

GENOMES = list(config["genomes"].keys())

## Samples and their corresponding filenames.
FILES = json.load(open(config['SAMPLES_JSON']))
SAMPLES = sorted(FILES.keys())

## Create the final output directory if it doesn't already exist
if not os.path.exists(OUT_DIR):
            os.makedirs(OUT_DIR)

ASE_LEVEL = config["ase_aggregation"]["level"]


##--------------------------------------------------------------------------------------##
#
# _____ _             _               _               _
#|  ___(_)_ __   __ _| |   ___  _   _| |_ _ __  _   _| |_ ___
#| |_  | | '_ \ / _` | |  / _ \| | | | __| '_ \| | | | __/ __|
#|  _| | | | | | (_| | | | (_) | |_| | |_| |_) | |_| | |_\__ \
#|_|   |_|_| |_|\__,_|_|  \___/ \__,_|\__| .__/ \__,_|\__|___/
#                                        |_|
##--------------------------------------------------------------------------------------##

## Final expected output(s)
rule all:
    input:
        expand(join(OUT_DIR, "ASE_feature", "{sample}_{genome}.snp_by_" + ASE_LEVEL + ".tsv", ), genome=config['genomes'], sample=SAMPLES),
        join(OUT_DIR, 'MultiQC', 'multiqc_report.html'),

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##
#  ___   ____
# / _ \ / ___|
#| | | | |
#| |_| | |___
# \__\_\\____|
#
##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule cutadapt:
    input:
        lambda wildcards: FILES[wildcards.sample]['R1'],
        lambda wildcards: FILES[wildcards.sample]['R2']
    output:
        fastq1 = join(OUT_DIR, 'trimmed_reads', '{sample}.1.fq.gz'),
        fastq2 = join(OUT_DIR, 'trimmed_reads', '{sample}.2.fq.gz'),
        qc = join(OUT_DIR, 'trimmed_reads', '{sample}.qc.txt')
    params:
        # https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-types
        adapters="-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -a CTGTCTCTTATACACATCT -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -A CTGTCTCTTATACACATCT",
        # https://cutadapt.readthedocs.io/en/stable/guide.html#
        extra="--minimum-length 50 -q 20"
    log:
        join(OUT_DIR, 'Logs', 'cutadapt', '{sample}.cutadapt.log')
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'cutadapt', '{sample}.cutadapt.benchmark.tsv')
    message:
        """--- Trimming adaptors for sample {wildcards.sample}."""
    threads:
        4
    resources:
        mem_mb=8000
    wrapper:
        "v3.10.2/bio/cutadapt/pe"

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule fastqc:
    input:
        r1 = lambda wildcards: FILES[wildcards.sample]['R1'],
        r2 = lambda wildcards: FILES[wildcards.sample]['R2'],
        fastq1 = join(OUT_DIR, 'trimmed_reads', '{sample}.1.fq.gz'),
        fastq2 = join(OUT_DIR, 'trimmed_reads', '{sample}.2.fq.gz'),
    output:
        r1 = join(OUT_DIR, 'fastQC', '{sample}.R1_fastqc.html'),
        r2 = join(OUT_DIR, 'fastQC', '{sample}.R2_fastqc.html'),
        fastq1 = join(OUT_DIR, 'fastQC', '{sample}.1_fastqc.html'),
        fastq2 = join(OUT_DIR, 'fastQC', '{sample}.2_fastqc.html'),
    params:
        out_dir = join(OUT_DIR, 'fastQC')
    log:
        join(OUT_DIR, 'Logs', 'fastQC', '{sample}.fastQC.log')
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'fastQC', '{sample}.fastQC.benchmark.tsv')
    message:
        """--- Checking read quality of sample "{wildcards.sample}" with FastQC """
    conda:
        'envs/rnaseq_yablab.yml'
    shell:
        """
        fastqc -o {params.out_dir} -t 4 -q {input.r1} {input.r2} {input.fastq1} {input.fastq2} > {log} 2>&1
        """

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##
#
# _____                   _      ____
#|_   _|   ___  _____  __| | ___|___ \
#  | || | | \ \/ / _ \/ _` |/ _ \ __) |
#  | || |_| |>  <  __/ (_| | (_) / __/
#  |_| \__,_/_/\_\___|\__,_|\___/_____|
#
#
##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##


rule hs2_exon_ss:
    input:
        gtf = lambda wildcards: config['genomes'][wildcards.genome]['gtf']
    output:
        exon = join(OUT_DIR, 'hs2_index', '{genome}', 'exon.txt'),
        ss = join(OUT_DIR, 'hs2_index', '{genome}', 'ss.txt') 
    threads:
        2
    message:
        """--- Extracting exon coordinates and splice sites for {wildcards.genome} genome """
    conda:
        'envs/rnaseq_yablab.yml'
    shell:
        """
        hisat2_extract_exons.py {input.gtf} > {output.exon}
        hisat2_extract_splice_sites.py {input.gtf} > {output.ss}
        """

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule hisat2_index:
    input:
        exon = join(OUT_DIR, 'hs2_index', '{genome}', 'exon.txt'),
        ss = join(OUT_DIR, 'hs2_index', '{genome}', 'ss.txt'),
        fasta = lambda wildcards: config['genomes'][wildcards.genome]['fasta']
    output:
        directory(join(OUT_DIR, 'hs2_index', 'index_{genome}'))
    params:
        prefix = join(OUT_DIR, 'hs2_index', 'index_{genome}/{genome}'),
        extra = lambda wc, input: f"--exon {input.exon} --ss {input.ss}"
    log:
        join(OUT_DIR, 'Logs', 'hisat2_index', '{genome}.log')
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'hisat2_index', '{genome}.benchmark.tsv')
    threads: 
        4
    wrapper:
        "v3.1.0/bio/hisat2/index"


##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule hisat2_align:
    input:
        reads = [join(OUT_DIR, 'trimmed_reads', '{sample}.1.fq.gz'), join(OUT_DIR, 'trimmed_reads', '{sample}.2.fq.gz')],
        idx = join(OUT_DIR, 'hs2_index', 'index_{genome}')
    output:
        bam = temp(join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.hisat2.bam'))
    log:
        join(OUT_DIR, 'Logs', 'hisat2', 'hisat2_{sample}_{genome}.log')
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'hisat2', 'hisat2_{sample}_{genome}.benchmark.tsv')
    params:
        extra="-p 8 --no-unal --dta --rg-id {sample} --rg ID:{sample} --rg SM:{sample}",
    threads: 8
    wrapper:
        "v3.12.1/bio/hisat2/align"


##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule samtools_sort:
    input:
        join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.hisat2.bam')
    output:
        join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.hisat2.bam')
    params:
        extra="-m 4G",
    threads: 8
    wrapper:
        "v3.12.1/bio/samtools/sort"

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule samtools_index:
    input:
        join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.hisat2.bam'),
    output:
        join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.hisat2.bam.bai'),
    log:
        join(OUT_DIR, 'Logs', 'samtools_index', '{sample}_{genome}.log'),
    params:
        extra="",  # optional params string
    threads: 4  # This value - 1 will be sent to -@
    wrapper:
        "v3.1.0/bio/samtools/index"

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule qualimap:
    input:
        # BAM aligned, splicing-aware, to reference genome
        bam = join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.hisat2.bam'),
        bai = join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.hisat2.bam.bai'),
        # GTF containing transcript, gene, and exon data
        gtf = lambda wildcards: config['genomes'][wildcards.genome]['gtf']
    output:
        directory(join(OUT_DIR, 'QC', '{genome}', '{sample}_{genome}_qualimap'))
    params:
        extra="--java-mem-size=32G -pe --outformat PDF"
    log:
        join(OUT_DIR, 'Logs', 'qualimap', 'qualmap_{sample}_{genome}.log')
    # optional specification of memory usage of the JVM that snakemake will respect with global
    # resource restrictions (https://snakemake.readthedocs.io/en/latest/snakefiles/rules.html#resources)
    # and which can be used to request RAM during cluster job submission as `{resources.mem_mb}`:
    # https://snakemake.readthedocs.io/en/latest/executing/cluster.html#job-properties
    wrapper:
        "v3.1.0/bio/qualimap/rnaseq"

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule stringtie:
    input:
        bam = join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.hisat2.bam')
    output:
        asmbly = temp(join(OUT_DIR, 'StringTie', '{genome}', '{sample}_{genome}.gtf'))
    params:
        gtf = lambda wildcards: config['genomes'][wildcards.genome]['gtf']
    log:
        join(OUT_DIR, 'Logs', 'stringtie', 'stringtie_{sample}_{genome}.log')
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'stringtie', 'stringtie_{sample}_{genome}.benchmark.tsv')
    threads:
        8
    resources:
        mem_mb=16000
    message:
        """--- Assembling transcripts for sample {wildcards.sample} with StringTie """
    conda:
        'envs/rnaseq_yablab.yml'
    shell:
        'stringtie'
                ' {input.bam}'
                ' -p 8'
                # ' -G {params.gtf}'
                ' -o {output.asmbly}'
                ' -l {wildcards.sample} > {log} 2>&1'

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule merge_assemblies:
    input:
        assemblies = expand(join(OUT_DIR, 'StringTie', '{genome}', '{sample}_{genome}.gtf'), sample = SAMPLES, genome = config['genomes'])
    output:
        asmbly = join(OUT_DIR, 'StringTie', '{genome}', 'stringtie_merged.gtf'),
        geneTransMap = join(OUT_DIR, 'StringTie', '{genome}', 'stringtie_merged_gene_trans_map')
    params:
        gtf = lambda wildcards: config['genomes'][wildcards.genome]['gtf']
    log:
        join(OUT_DIR, 'Logs', 'stringtie', 'st_mrg_{genome}.log')
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'stringtie', 'st_mrg_{genome}.benchmark.tsv')
    threads:
        8
    resources:
        mem_mb=16000
    message:
        """--- Merging StringTie transcripts for genome mapping {wildcards.genome}"""
    conda:
        'envs/rnaseq_yablab.yml'
    shell:
        'ls -1 ' + join(OUT_DIR, 'StringTie', '{wildcards.genome}', '*.gtf') + ' > ' + join(OUT_DIR, 'StringTie', '{wildcards.genome}', 'assemblies.txt') + 
        ' && stringtie'
                ' --merge'
                ' -p 8'
                # ' -G {params.gtf}'
                ' -o {output.asmbly} ' + join(OUT_DIR, 'StringTie', '{wildcards.genome}', 'assemblies.txt') +
        ' && awk \'{{if ($3 == "transcript") print $10"\t"$12}}\' {output.asmbly} | sed "s/;//g" | sed "s/\\\"//g" | sort -u > {output.geneTransMap}'

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule repeatmasker:
    input:
        fasta = lambda wildcards: config['genomes'][wildcards.genome]['fasta'],
        asmbly = join(OUT_DIR, 'StringTie', '{genome}', 'stringtie_merged.gtf')
    output:
        folder = directory(join(OUT_DIR, 'RepeatMasker', '{genome}')),
        fasta = join(OUT_DIR, 'RepeatMasker', '{genome}_RM_TEs.fasta'),
        gtf = join(OUT_DIR, 'RepeatMasker', '{genome}_RM_TEs.gtf')
    log:
        join(OUT_DIR, 'Logs', 'repeatmasker', '{genome}.log')
    params:
        te_lib = lambda wildcards: config['genomes'][wildcards.genome]['te_fasta'] 
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'repeatmasker', '{genome}.benchmark.tsv')
    threads:
        16
    resources:
        mem_mb=16000,
        repeatmasker_db=1       # <-- mutex for the library build
    message:
        """--- Masking repeates for {wildcards.genome} genome """
    conda:
        'envs/repeatmasker.yml'
    shell:
        (
        'RepeatMasker'
        ' -e ncbi'
        ' -q'
        ' -no_is'
        ' -nolow'
        ' -gff'
        ' -lib {params.te_lib}'
        ' -dir {output.folder}'
        ' {input.fasta}'
        ' > {log} 2>&1'
        ' && cat ' + join(OUT_DIR, 'RepeatMasker', '{wildcards.genome}', '*.masked') + ' {params.te_lib} > {output.fasta}'
        ' && awk \'/^>/ {{if (seqlen){{print seqlen}}; print ;seqlen=0;next; }} {{ seqlen += length($0)}}END{{print seqlen}}\' {params.te_lib} | tr \'\\n\' \'\\t\' | sed "s/$/\\n/g" | tr \'>\' \'\\n\' | awk \'{{print $1"\\tRepeatMasker\\texon\\t1\\t"$4"\\t.\\t+\\t.\\tgene_id \\""$1"\\"; gene_name \\""$1"\\"; gene_biotype \\"protein_coding\\";"}}\' | sed 1d | cat {input.asmbly} - > {output.gtf}'
        )

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule RM_seqDictionary:
    input:
        fasta = join(OUT_DIR, 'RepeatMasker', '{genome}_RM_TEs.fasta')
    output:
        join(OUT_DIR, 'RepeatMasker', '{genome}_RM_TEs.dict'),
        join(OUT_DIR, 'RepeatMasker', '{genome}_RM_TEs.fasta.fai')
    log:
        join(OUT_DIR, 'Logs', 'seqDictionary', '{genome}_RM.log')
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'seqDictionary', '{genome}_RM.benchmark.tsv')
    threads: 
        4
    conda:
        'envs/atac_yablab.yml'
    message:
        """--- Creating sequence dictionary for {wildcards.genome} RM genome. """
    shell:
        'picard CreateSequenceDictionary'
                ' -R {input.fasta}'
                ' > {log} 2>&1'
        ' && samtools faidx {input.fasta}'

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule hisat2_RM_index:
    input:
        fasta = join(OUT_DIR, 'RepeatMasker', '{genome}_RM_TEs.fasta'),
        exon = join(OUT_DIR, 'hs2_index', '{genome}', 'exon.txt'),
        ss = join(OUT_DIR, 'hs2_index', '{genome}', 'ss.txt'),
    output:
        directory(join(OUT_DIR, 'RepeatMasker', 'hs2_index', 'index_{genome}'))
    params:
        prefix = join(OUT_DIR, 'RepeatMasker', 'hs2_index', 'index_{genome}/{genome}'),
        extra = lambda wc, input: f"--exon {input.exon} --ss {input.ss}"
    log:
        join(OUT_DIR, 'Logs', 'hisat2_index', '{genome}_RM.log')
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'hisat2_index', '{genome}_RM.benchmark.tsv')
    threads: 
        4
    wrapper:
        "v3.12.1/bio/hisat2/index"

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule hisat2_RM_align:
    input:
        reads = [join(OUT_DIR, 'trimmed_reads', '{sample}.1.fq.gz'), join(OUT_DIR, 'trimmed_reads', '{sample}.2.fq.gz')],
        idx = join(OUT_DIR, 'RepeatMasker', 'hs2_index', 'index_{genome}')
    output:
        bam = temp(join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}_RM.hisat2.bam'))
    log:
        join(OUT_DIR, 'Logs', 'hisat2', 'hisat2_{sample}_{genome}_RM.log')
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'hisat2', 'hisat2_{sample}_{genome}_RM.benchmark.tsv')
    params:
        extra="-p 8 --no-unal --dta --rg-id {sample} --rg ID:{sample} --rg SM:{sample}",
    threads: 8
    wrapper:
        "v3.12.1/bio/hisat2/align"

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule samtools_RM_sort:
    input:
        join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}_RM.hisat2.bam')
    output:
        join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.RM.hisat2.bam')
    log:
        join(OUT_DIR, 'Logs', 'hisat2', 'samtools_sort_{sample}_{genome}_RM.log')
    params:
        extra="-m 4G",
    threads: 8
    wrapper:
        "v3.12.1/bio/samtools/sort"

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule samtools_RM_index:
    input:
        join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.RM.hisat2.bam'),
    output:
        join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.RM.hisat2.bam.bai'),
    log:
        join(OUT_DIR, 'Logs', 'samtools_index', '{sample}_{genome}_RM.log'),
    params:
        extra="",  # optional params string
    threads: 4  # This value - 1 will be sent to -@
    wrapper:
        "v3.1.0/bio/samtools/index"

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

## measure transcript abundances with Stringtie
rule featureCounts:
    input:
        hbams = expand(join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.hisat2.bam'), sample = SAMPLES, genome = config['genomes']),
        mrgd = join(OUT_DIR, 'StringTie', '{genome}', 'stringtie_merged.gtf')
    output:
        countsSt = join(OUT_DIR, 'abundances', '{genome}', 'stringtie_gene_counts.txt'),
        countsStMatrix = join(OUT_DIR, 'abundances', '{genome}', 'stringtie_gene_counts_matrix.txt')
    params:
        hbam_dir = join(OUT_DIR, 'HISAT-2', '{wildcards.genome}', '*.csorted.hisat2.bam'),
    log:
        join(OUT_DIR, 'Logs', 'abundances', '{genome}_fC.log')
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'abundances', '{genome}_fC.benchmark.tsv')
    threads:
        8
    resources:
        mem_mb=16000
    conda:
        'envs/rnaseq_yablab.yml'
    message:
        """--- Outputting gene counts with featureCounts for {wildcards.genome} genome mapping. """
    shell:
        """
        featureCounts -a {input.mrgd} -p -T {threads} -F GTF -o {output.countsSt} {params.hbam_dir} > {log} 2>&1
        cat {output.countsSt} | cut -f 1,7- | sed 1d > {output.countsStMatrix}
        """

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule featureCounts_RM:
    input:
        bams = expand(join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.RM.hisat2.bam'), sample = SAMPLES, genome = config['genomes']),
        gtf = join(OUT_DIR, 'RepeatMasker', '{genome}_RM_TEs.gtf')
    output:
        countsSt = join(OUT_DIR, 'abundances_RM', '{genome}', 'stringtie_RM_gene_counts.txt'),
        countsStMatrix = join(OUT_DIR, 'abundances_RM', '{genome}', 'stringtie_RM_gene_counts_matrix.txt')
    params:
        bam_dir = join(OUT_DIR, 'HISAT-2', '{wildcards.genome}', '*.csorted.RM.hisat2.bam')
    log:
        join(OUT_DIR, 'Logs', 'abundances_RM', '{genome}_RM_fC.log')
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'abundances_RM', '{genome}_RM_fC.benchmark.tsv')
    threads:
        8
    resources:
        mem_mb=16000
    conda:
        'envs/rnaseq_yablab.yml'
    message:
        """--- Outputting gene counts with featureCounts for repeat-masked {wildcards.genome} genome mapping. """
    shell:
        """
        featureCounts -a {input.gtf} -p -T {threads} -F GTF -o {output.countsSt} {params.bam_dir} > {log} 2>&1
        cat {output.countsSt} | cut -f 1,7- | sed 1d > {output.countsStMatrix}
        """

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##
#     _    ____  _____ 
#    / \  / ___|| ____|
#   / _ \ \___ \|  _|  
#  / ___ \ ___) | |___ 
# /_/   \_\____/|_____|
#
##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule MarkDuplicates:
    input:
        bam = join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.hisat2.bam')
    output:
        bam = temp(join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.duprem.hisat2.bam'))
    log:
        stdout = join(OUT_DIR, 'Logs', 'MarkDups', '{sample}_{genome}_markdups.log'),
        metrics = join(OUT_DIR, 'Benchmarks', 'MarkDups', '{sample}_{genome}_metrics.benchmark.tsv')
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'MarkDups', '{sample}_{genome}_markdups.benchmark.tsv')
    threads:
        8
    resources:
        mem_mb=16000
    message:
        """--- Marking and removing duplicates for sample {wildcards.sample} with {wildcards.genome} mapping """
    conda:
        'envs/atac_yablab.yml'
    shell:
        'picard -Xmx{resources.mem_mb}m MarkDuplicates'
                ' -I {input.bam}'
                ' --MAX_RECORDS_IN_RAM 2000000'
                ' -O {output.bam}'
                ' -M {log.metrics}'
                ' --TMP_DIR ' + join(OUT_DIR, 'Temp', 'picard', '{wildcards.genome}', '{wildcards.sample}') +
                ' --REMOVE_DUPLICATES true'
                ' > {log.stdout} 2>&1'


##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule SplitNCigarReads:
    input:
        bam = join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.duprem.hisat2.bam')
    output:
        bam = join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.duprem.split.hisat2.bam'),
    params:
        fasta = lambda wildcards: config['genomes'][wildcards.genome]['fasta']
    log:
        join(OUT_DIR, 'Logs', 'SplitCigR', '{sample}_{genome}_splitcigar.log') 
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'SplitCigR', '{sample}_{genome}_splitcigar.benchmark.tsv')
    threads:
        8
    resources:
        mem_mb=16000
    message:
        """--- Splitting N CIGAR reads for sample {wildcards.sample} with {wildcards.genome} mapping """
    conda:
        'envs/gatk.yml'
    shell:
        """
        gatk SplitNCigarReads -R {params.fasta} -I {input.bam} -O {output.bam}
        """

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule exonIntervals:
    input:
        asmbly = join(OUT_DIR, 'StringTie', '{genome}', 'stringtie_merged.gtf')
    output:
        exons_bed = join(OUT_DIR, 'ASEReadCounter_star', '{genome}', 'vcf_out', 'EXONS.bed')
    log:
        join(OUT_DIR, 'Logs','ASEReadCounter_star', '{genome}', 'exons_bed.log')
    benchmark:
        join(OUT_DIR, 'Benchmarks','ASEReadCounter_star', '{genome}', 'exons_bed.benchmark.tsv')
    threads:
        8
    resources:
        mem_mb=16000
    message:
        """--- Extracting exon coordinates for {wildcards.genome} genome"""
    run:
        shell('awk \'$3=="exon"\' {input.asmbly} | cut -f1,4,5,9 | awk -F $"\t" \'BEGIN {{OFS = FS}} {{split($4, a, "gene_id \\""); split(a[2], b, "\\""); print $1, $2-1, $3, b[1]}}\' > {output.exons_bed}')

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule HaplotypeCaller:
    input:
        bam = join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.duprem.split.hisat2.bam'),
        exons_bed = join(OUT_DIR, 'ASEReadCounter_star', '{genome}', 'vcf_out', 'EXONS.bed')
    output:
        vcf = join(OUT_DIR, 'GATK', '{genome}', '{sample}_{genome}.haplo.SNP.vcf.gz'),
    params:
        fasta = lambda wildcards: config['genomes'][wildcards.genome]['fasta']
    log:
        join(OUT_DIR, 'Logs', 'HaplotypeCaller', '{sample}_{genome}_haplo.log') 
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'HaplotypeCaller', '{sample}_{genome}_haplo.benchmark.tsv')
    threads:
        8
    resources:
        mem_mb=16000
    message:
        """--- Calling variants for sample {wildcards.sample} with {wildcards.genome} mapping """
    conda:
        'envs/gatk.yml'
    shell:
        """
        gatk HaplotypeCaller -R {params.fasta} -I {input.bam} -O {output.vcf} -L {input.exons_bed} \
            -stand-call-conf 20 -dont-use-soft-clipped-bases -ERC GVCF > {log} 2>&1
        """

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule GenotypeGVCFs:
    input:
        vcf = join(OUT_DIR, 'GATK', '{genome}', '{sample}_{genome}.haplo.SNP.vcf.gz')
    output:
        vcf = join(OUT_DIR, 'GATK', '{genome}', '{sample}_{genome}.genotype_SNP.vcf.gz'),
    params:
        fasta = lambda wildcards: config['genomes'][wildcards.genome]['fasta']
    log:
        join(OUT_DIR, 'Logs', 'GenotypeGVCFs', '{sample}_{genome}_genoVCF.log') 
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'GenotypeGVCFs', '{sample}_{genome}_genoVCF.benchmark.tsv')
    threads:
        8
    resources:
        mem_mb=16000
    message:
        """--- Calling genotypes for sample {wildcards.sample} with {wildcards.genome} mapping """
    conda:
        'envs/gatk.yml'
    shell:
        """
        gatk GenotypeGVCFs -R {params.fasta} -V {input.vcf} -O {output.vcf} --max-alternate-alleles 4 \
            --standard-min-confidence-threshold-for-calling 30 -all-sites > {log} 2>&1
        """

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule VariantFiltration:
    input:
        vcf = join(OUT_DIR, 'GATK', '{genome}', '{sample}_{genome}.genotype_SNP.vcf.gz')
    output:
        vcf = join(OUT_DIR, 'GATK', '{genome}', '{sample}_{genome}.genotype_SNP.filtered.vcf'),
    params:
        fasta = lambda wildcards: config['genomes'][wildcards.genome]['fasta']
    log:
        join(OUT_DIR, 'Logs', 'GenotypeGVCFs', '{sample}_{genome}_genoVCF.log') 
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'GenotypeGVCFs', '{sample}_{genome}_genoVCF.benchmark.tsv')
    threads:
        8
    resources:
        mem_mb=16000
    message:
        """--- Filtering variants for sample {wildcards.sample} with {wildcards.genome} mapping """
    conda:
        'envs/gatk.yml'
    shell:
        """
        gatk VariantFiltration -R {params.fasta} -V {input.vcf} -O {output.vcf} --window 35 --cluster 3 --filter-name "DP" --filter "DP < 5" \
            --filter-name "FS" --filter "FS > 30.0" --filter-name "QD" --filter "QD < 2.0" > {log} 2>&1
        """

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule SelectVariants:
    input:
        vcf = join(OUT_DIR, 'GATK', '{genome}', '{sample}_{genome}.genotype_SNP.filtered.vcf')
    output:
        vcf = join(OUT_DIR, 'GATK', '{genome}', '{sample}_{genome}.genotype_SNP.filtered.PASS.vcf'),
    params:
        fasta = lambda wildcards: config['genomes'][wildcards.genome]['fasta']
    log:
        join(OUT_DIR, 'Logs', 'SelectVariants', '{sample}_{genome}_selVar.log') 
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'SelectVariants', '{sample}_{genome}_selVar.benchmark.tsv')
    threads:
        8
    resources:
        mem_mb=16000
    message:
        """--- Selecting variants for sample {wildcards.sample} with {wildcards.genome} mapping """
    conda:
        'envs/gatk.yml'
    shell:
        """
        gatk SelectVariants -V {input.vcf} -O {output.vcf} --exclude-filtered --restrict-alleles-to BIALLELIC --select-type-to-include SNP > {log} 2>&1
        """

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule ASEReadCounter:
    input:
        bam = join(OUT_DIR, 'HISAT-2', '{genome}', '{sample}_{genome}.csorted.duprem.split.hisat2.bam'),
        vcf = join(OUT_DIR, 'GATK', '{genome}', '{sample}_{genome}.genotype_SNP.filtered.PASS.vcf')
    output:
        ase = join(OUT_DIR, 'GATK', '{genome}', '{sample}_{genome}.SNP.ASE.RNAFixed.ALL.output.table'),
    params:
        fasta = lambda wildcards: config['genomes'][wildcards.genome]['fasta']
    log:
        join(OUT_DIR, 'Logs', 'SelectVariants', '{sample}_{genome}_selVar.log') 
    benchmark:
        join(OUT_DIR, 'Benchmarks', 'SelectVariants', '{sample}_{genome}_selVar.benchmark.tsv')
    threads:
        8
    resources:
        mem_mb=16000
    message:
        """--- Counting allele-specific reads for sample {wildcards.sample} with {wildcards.genome} mapping """
    conda:
        'envs/gatk.yml'
    shell:
        """
        gatk ASEReadCounter -R {params.fasta} -I {input.bam} -V {input.vcf} -O {output.ase} --disable-sequence-dictionary-validation > {log} 2>&1
        """

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule aggregate_ase_by_feature:
    input:
        gtf = join(OUT_DIR, "StringTie", "{genome}", "stringtie_merged.gtf"),
        ase = join(OUT_DIR, 'GATK', '{genome}', '{sample}_{genome}.SNP.ASE.RNAFixed.ALL.output.table'),
    output:
        snp_by_feature = join(
            OUT_DIR,
            "ASE_feature",
            "{sample}_{genome}.snp_by_{ASE_LEVEL}.tsv",
        ),
        ase_by_feature = join(
            OUT_DIR,
            "ASE_feature",
            "{sample}_{genome}.ase_by_{ASE_LEVEL}.tsv",
        ),
    params:
        prefix = lambda wc, output: output.snp_by_feature.replace(
            f".snp_by_{ASE_LEVEL}.tsv", ""
        ),
        level = lambda wc: config["ase_aggregation"]["level"],
        feature_type = lambda wc: config["ase_aggregation"]["feature_type"],
        agg = lambda wc: config["ase_aggregation"]["aggregation"],
        min_total_count = lambda wc: config["ase_aggregation"]["min_total_count"],
    conda:
        "envs/ase_aggregation.yml"
    threads:
        2
    message:
        "Aggregating ASE for {wildcards.sample} on {wildcards.genome} at {params.level} level"
    shell:
        """
        mkdir -p $(dirname {output.snp_by_feature})
        aggregate_ase_by_feature.py --gtf {input.gtf}--ase {input.ase} --level {params.level} --feature-type {params.feature_type} \
            --agg {params.agg} --min-total-count {params.min_total_count} -o {params.prefix}
        """

##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##
# __  __       _ _   _  ___   ____
#|  \/  |_   _| | |_(_)/ _ \ / ___|
#| |\/| | | | | | __| | | | | |
#| |  | | |_| | | |_| | |_| | |___
#|_|  |_|\__,_|_|\__|_|\__\_\\____|
#
##--------------------------------------------------------------------------------------##
##--------------------------------------------------------------------------------------##

rule multiQC:
    input:
        expand(join(OUT_DIR, 'fastQC', '{sample}.R1_fastqc.html'), sample = SAMPLES),
        expand(join(OUT_DIR, 'fastQC', '{sample}.1_fastqc.html'), sample = SAMPLES),
        expand(join(OUT_DIR, 'trimmed_reads', '{sample}.qc.txt'), sample = SAMPLES),
        expand(join(OUT_DIR, 'Logs', 'hisat2', 'hisat2_{sample}_{genome}.log'), sample = SAMPLES, genome = config['genomes']),
        expand(join(OUT_DIR, 'Logs', 'hisat2', 'hisat2_{sample}_{genome}_RM.log'), sample = SAMPLES, genome = config['genomes']),
        expand(join(OUT_DIR, 'Logs', 'qualimap', 'qualmap_{sample}_{genome}.log'), sample = SAMPLES, genome = config['genomes']),
        expand(join(OUT_DIR, 'Logs', 'abundances', '{genome}_fC.log'), genome = config['genomes']),
        expand(join(OUT_DIR, 'Logs', 'abundances_RM', '{genome}_RM_fC.log'), genome = config['genomes'])
    output:
        join(OUT_DIR, 'MultiQC', 'multiqc_report.html')
    params:
        summary_files = join(OUT_DIR, 'MultiQC', 'summary_files.txt'),
        fastQC = join(OUT_DIR, 'fastQC', '*fastqc.zip'),
        trimmed_reads = join(OUT_DIR, 'trimmed_reads', '*qc.txt'),
        hisat2 = join(OUT_DIR, 'Logs', 'hisat2', 'hisat2_*log'),
        qualimap = join(OUT_DIR, 'QC', '*', '*_qualimap'),
        abundances = join(OUT_DIR, 'abundances*', '*', '*summary'),
        out_dir = join(OUT_DIR, 'MultiQC'),
    log:
        join(OUT_DIR, 'MultiQC', 'multiQC.log')
    benchmark:
        join(OUT_DIR, 'MultiQC', 'multiQC.benchmark.tsv')
    conda:
        'envs/rnaseq_yablab.yml'
    message:
        """--- Running MultiQC """
    shell:
        """
        ls -1 {params.fastQC} >> {params.summary_files}
        ls -1 {params.trimmed_reads} >> {params.summary_files}
        ls -1 {params.hisat2} >> {params.summary_files}
        ls -1 {params.qualimap} | grep ":" | sed "s/://g" >> {params.summary_files}
        ls -1 {params.abundances} >> {params.summary_files}
        multiqc -f -o {params.out_dir} -l {params.summary_files} > {log} 2>&1
        """
